### PR TITLE
mirror: Add .mailmap to the repository, sync with kernel's

### PR DESCRIPTION
**Pull request by qmonnet**
Add a script to grep for the relevant entries in the .mailmap file of the kernel repository, and use it to build a .mailmap file for the mirror repo.

### CODE REVIEW

**Comment by qmonnet** [comment]
Cc @anakryiko just for your information, in case you were interested in a `.mailmap` for libbpf.

**Comment by anakryiko** [comment]
how is this .mailmap file used? Is Github using this automatically?

If you are up sending PR, we can add it to libbpf repo and maybe include it into sync workflow.

**Comment by qmonnet** [comment]
> how is this .mailmap file used? Is Github using this automatically?

The .mailmap is used by git to remap names or emails in commit logs, typically if someone didn't use a canonical form for their name, or if they changed email address. See [the documentation](https://git-scm.com/docs/gitmailmap) for details.

Concretely, if you cloned the repository and run `git log` in it, you would no longer see my @isovalent.com email for the commits I authored, only the @kernel.org (the sign-offs and other tags in commit description remain unchanged, though).

Alas, GitHub [does not support mailmap](https://github.com/orgs/community/discussions/22518) as far as I know. So it's only when you look locally at the logs, which makes the interest of the whole thing limited, but I thought it would still be nice to replicate this aspect from the kernel repo and account for email address changes when relevant.

> If you are up sending PR, we can add it to libbpf repo and maybe include it into sync workflow.

Should be easy enough, the update script I merged works just as well for libbpf, and we can call it from the sync-up script. I'll send the PR.

**Comment by qmonnet** [comment]
https://github.com/libbpf/libbpf/pull/800

**Pull request merged**
